# general
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -ag terminal-overrides ",xterm-256color:RGB"

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded"

# Reset default command
set-option -g default-command ""

# Renumber all windows when any window is closed
set -g renumber-windows on

# Vi mode for copy
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Session controls
bind R command-prompt -I "#S" "rename-session -- '%%'"
bind C new-session -c "#{pane_current_path}"
bind K kill-session
bind P switch-client -p
bind N switch-client -n

# Pane Controls
bind x kill-pane

# Split horizontally with |
unbind %
bind '\' split-window -h

# Split vertically with -
unbind '"'
bind '-' split-window -v

# Resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Maximize pane toggle using m
bind -r m resize-pane -Z

# Status bar
set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{pane_current_command}'


# Adds spacing to the tmux status bar
set -g status 2
set -g status-format[1] ""
