set -g @powerkit_plugins "git,github,cpu,memory,uptime"

set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "mocha"

# set -g @powerkit_separator_style "rounded"
# set -g @powerkit_edge_separator_style "rounded:all"

set -g @powerkit_status_interval "5"

set -g @powerkit_transparent "true"

set -g @powerkit_status_order "windows,session,plugins"

set -g @powerkit_lazy_loading "true"
